feat/#60
openuniland/revise-fe pull request #63
Opened 2023-04-06 15:32 UTC by DungNguyen2003

2023-04-06 16:42 UTC, nc-minh commented
@DungNguyen2003 pls resolve conflict.

2023-04-06 17:10 UTC, DungNguyen2003 commented
done _-_

2023-04-07 02:18 UTC, nc-minh requested changes

2023-04-07 02:18 UTC, nc-minh commented on src/app/containers/TestShow/index.tsx
> +    [examDuration],
missing durationError in dependencies

2023-04-07 02:18 UTC, nc-minh commented on src/app/containers/TestShow/index.tsx
> +  }, [examDuration]);
missing some dependencies

2023-04-07 02:18 UTC, nc-minh commented on src/app/components/PopupDuration/index.tsx
> +import { LoadingButton } from "@mui/lab";
Why do you need to create this component? If you want to create a custom popup it has already been defined in **_ModalCustomization_** component

2023-04-07 17:36 UTC, DungNguyen2003 commented
fixed =_=

2023-04-08 08:12 UTC, nc-minh approved these changes

2023-04-08 08:12 UTC, merged